version: '3'
services:
  app:
    container_name: api.locadora
    build:
      context: .
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    depends_on:
      - database

  server:
    container_name: nginx.locadora
    image: nginx:1.17.9
    working_dir: /app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  database:
    container_name: mongodb.locadora
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: docker
      MONGO_INITDB_ROOT_PASSWORD: docker